version: '3.8'

services:
  backend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6380  # Updated port for Redis
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6380:6379"  # Map host port 6380 to container port 6379
