# Generated by Django 5.1.3 on 2024-11-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_stamped',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
